# AI.Programming.101 - Week 3 실습
## 데이터 분석의 핵심: NumPy와 Pandas (그리고 R, JAX 비교)

이번 주에는 파이썬 데이터 분석의 필수 라이브러리인 **NumPy**와 **Pandas**의 기초 문법을 학습합니다.\n
또한 데이터 분석에서의 R 언어와의 차이점과 최신 AI 연산 도구인 JAX와의 차이점도 함께 비교합니다.

---

### 1. R 언어와 Python (Pandas) 비교

R 언어는 통계학자와 데이터 분석가를 위해 설계된 언어로 데이터프레임 구조를 언어 차원에서 기본적으로 지원합니다.\n
Python은 범용 언어이기 때문에 `pandas` 라이브러리를 통해 이 기능을 제공합니다.\n
아래는 R의 기본 `data.frame` 연산이 Pandas에서 어떻게 구현되는지 비교한 예시입니다.

In [1]:
import pandas as pd 

# [R 언어 방식의 상상 코드]
# df <- data.frame(Name=c('Alice', 'Bob'), Age=c(24, 27))
# subset(df, Age > 25)

# [Python Pandas 방식]
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}
df = pd.DataFrame(data)

print("전체 데이터프레임:\n", df)
print("\n25세 이상 필터링 (R의 subset 역할):\n", df[df['Age'] > 25])

전체 데이터프레임:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32

25세 이상 필터링 (R의 subset 역할):
     Name  Age
1    Bob   27
3  David   32


---

### 2. NumPy 기초

In [2]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1차원 배열:", arr1)
print("Shape:", arr1.shape)

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2차원 배열:\n", arr2)
print("Shape:", arr2.shape)

1차원 배열: [1 2 3 4 5]
Shape: (5,)

2차원 배열:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


#### 2.1 기본 연산과 브로드캐스팅

In [3]:
# 배열 간의 연산 (Element-wise)
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print("a + b =", a + b)
print("a * b =", a * b)

# 브로드캐스팅: 스칼라값(단일 숫자)과의 연산도 자동으로 적용됩니다.
print("\na + 5 =", a + 5)

a + b = [11 22 33]
a * b = [10 40 90]

a + 5 = [15 25 35]


---

### 3. JAX vs NumPy (R깔아야 함)
JAX는 고성능 머신러닝 연구를 위해 구글에서 개발한 라이브러리로, GPU/TPU 가속과 자동 미분(AutoGrad) 기능이 내장된 **'강력한 버전의 NumPy'** 입니다.
`jax.numpy`의 문법은 기존 `numpy`와 99% 일치하지만 더 강력합니다.

In [1]:
# 주의: 환경에 따라 jax 모듈이 설치되어 있어야 실행됩니다.
# !pip install jax jaxlib
try:
    import jax.numpy as jnp
    from jax import grad
    
    # JAX를 이용한 배열 생성 (문법이 numpy와 동일)
    j_arr = jnp.array([10., 20., 30.])
    print("JAX 배열 (DeviceArray):", j_arr)
    print("JAX 연산 (j_arr * 2) =", j_arr * 2)
    
    # 자동미분 맛보기: 함수 f(x) = x^2
    def f(x):
        return x**2
    
    # f(x)의 도함수 생성 (2x)
    df = grad(f)
    
    print("\nf(3.0) =", f(3.0))         # 9.0
    print("f'(3.0) [미분값] =", df(3.0)) # 6.0
    
except ImportError:
    print("현재 환경에 jax가 설치되어 있지 않습니다. `pip install jax jaxlib`을 통해 설치 후 실행해보세요.")

JAX 배열 (DeviceArray): [10. 20. 30.]
JAX 연산 (j_arr * 2) = [20. 40. 60.]

f(3.0) = 9.0
f'(3.0) [미분값] = 6.0


---

---
### 4. Python에서 R 함수 사용하기 (rpy2 라이브러리) (R깔아야 함)

`rpy2` 라이브러리를 사용하면 Python 스크립트나 Jupyter Notebook 내에서 직접 R 코드를 실행하고 데이터를 주고받을 수 있습니다.\n
Jupyter Notebook에서는 `%%R` 매직 커맨드를 이용해 R 셀을 바로 사용할 수도 있습니다.

In [2]:
# 주의: 이 코드를 실행하려면 rpy2 라이브러리와 R이 시스템에 설치되어 있어야 합니다.
# !pip install rpy2
try:
    import rpy2.robjects as robjects
    from rpy2.robjects.packages import importr
    
    # R의 기본 내장 함수(base) 로드
    base = importr('base')
    
    # 파이썬에서 R의 sum 함수 호출 연습
    # R 코드: sum(c(1, 2, 3, 4, 5))
    r_vector = robjects.FloatVector([1.5, 2.5, 3.5])
    result = base.sum(r_vector)
    
    print("Python 배열을 R로 넘겨 sum() 함수를 돌린 결과:", result[0])
    
    # R 코드를 문자열로 직접 실행
    r_script = '''
    my_func <- function(x) {
        return(mean(x) + 10)
    }
    '''
    robjects.r(r_script)
    r_my_func = robjects.globalenv['my_func']
    print("\nR 스크립트로 정의한 my_func(c(10, 20)) 결과:", r_my_func(robjects.FloatVector([10, 20]))[0])
    
except ImportError:
    print("rpy2 모듈이 설치되어 있지 않습니다. pip install rpy2 를 통해 설치할 수 있습니다.")
except Exception as e:
    print("R이 제대로 동작하지 않습니다 (경로 확인 필요):", e)

rpy2 모듈이 설치되어 있지 않습니다. pip install rpy2 를 통해 설치할 수 있습니다.


Jupyter 노트북에서 **`%load_ext rpy2.ipython`** 을 실행한 후, **`%%R`** 매직 커맨드를 사용하면 아래와 같이 하나의 셀 전체를 R 환경처럼 사용할 수 있습니다.

In [9]:
# %load_ext rpy2.ipython
## 아래 코드를 주석 해제 후 실행하면 R 환경에서 곧바로 코딩하는 것과 같이 동작합니다.
# %%R
# print("Hello from R!")
# data <- c(1, 2, 3, 4, 5)
# summary(data)

---
### 5. [심화] 고윳값(Eigenvalue)과 특이값 분해(SVD) ##중요

유사 역행렬(Pseudo Inverse)을 이해하기 위한 필수 뼈대 지식입니다.\n
데이터의 주요 축을 찾거나(PCA 차원 축소) 직사각형 행렬을 다루기 위해 **고윳값 분해(Eigendecomposition)**와 **특이값 분해(SVD)**를 학습합니다.

왜 고윳값, 고육벡터를 사용해야 하냐?
고유벡터를 찾는 다는 것의 의미: 
삐뚫어져있는 기저벡터나 좌표계 (즉, 복잡한 현실세상)를 잘 정렬되어있는 기저벡터로 되돌려놓는 벡터가 고유벡터다. 

In [4]:
import numpy as np

# -----------------------------------
# 1. 고윳값(Eigenvalue)과 고유벡터(Eigenvector)
# -----------------------------------
# (정방행렬 2x2)
A_sq = np.array([
    [4, 1],
    [2, 3]
])

print("=== 정방행렬 A_sq ===\n", A_sq)

# 고윳값(eigenvalues)과 고유벡터(eigenvectors) 계산
eigenvalues, eigenvectors = np.linalg.eig(A_sq)

print("\n고윳값 (Eigenvalues):", eigenvalues)
print("고유벡터 (Eigenvectors):\n", eigenvectors)

# 검증: A * v = lambda * v
v0 = eigenvectors[:, 0]    # 첫번째 고유벡터
lambda0 = eigenvalues[0]   # 첫번째 고윳값

print("\n검증 (A * v0):", np.dot(A_sq, v0))
print("검증 (lambda0 * v0):", lambda0 * v0)
print("(두 결과가 같으면 수학적으로 올바른 것입니다!)")

=== 정방행렬 A_sq ===
 [[4 1]
 [2 3]]

고윳값 (Eigenvalues): [5. 2.]
고유벡터 (Eigenvectors):
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

검증 (A * v0): [3.53553391 3.53553391]
검증 (lambda0 * v0): [3.53553391 3.53553391]
(두 결과가 같으면 수학적으로 올바른 것입니다!)


In [5]:
# -----------------------------------
# 2. 특이값 분해 (Singular Value Decomposition, SVD)
# -----------------------------------
# (직사각형 행렬 3x2 - 앞선 데이터 예시)
A_rect = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("=== 직사각형 행렬 A_rect (3x2) ===\n", A_rect)

# 특이값 분해 (A = U * Sigma * V^T)
# U: (3x3) 왼쪽 특이벡터 행렬
# S: (2,) 1차원 배열로 된 특이값 (Singular values)
# VT: (2x2) 오른쪽 특이벡터 행렬
U, S, VT = np.linalg.svd(A_rect)

print("\nU 행렬 (행 차원 회전):\n", U)
print("\n특이값 S (중요도/크기, 내림차순):", S) # S 데이터가 분산/정보량을 대변합니다
print("\nVT 행렬 (열 차원 회전):\n", VT)

=== 직사각형 행렬 A_rect (3x2) ===
 [[1 2]
 [3 4]
 [5 6]]

U 행렬 (행 차원 회전):
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

특이값 S (중요도/크기, 내림차순): [9.52551809 0.51430058]

VT 행렬 (열 차원 회전):
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


---
### 6. [심화] 유사 역행렬 (Pseudo Inverse)
공학에서 정방행렬을 거의 존재하지 않음. 항상 필요한 개념임.

정방행렬(N x N)이 아닌 행렬에 대해서도 역행렬과 비슷한 역할을 하는 행렬을 구하는 방법입니다.\n
머신러닝의 기초 알고리즘 중 평범한 '선형 회귀(Linear Regression)'의 최적 파라미터(가중치)를 오차 없이 단번에 계산할 때 사용됩니다.\n

NumPy에서는 `np.linalg.pinv(A)` 함수를 사용하여 구할 수 있습니다.

In [6]:
import numpy as np

# 1. 3행 2열의 직사각형 행렬 A (정방행렬이 아님)
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

print("원본 행렬 A (3x2):\n", A)

# 2. 유사 역행렬 계산 (Moore-Penrose Pseudo Inverse)
A_pinv = np.linalg.pinv(A)

print("\n유사 역행렬 A_pinv (2x3):\n", A_pinv)

# 3. 유사 역행렬의 성질 확인 (A_pinv * A = I, 항등행렬)
# 완벽한 항등행렬이 나오는지 확인해봅시다. (소수점 아래 미세 오차 무시)
identity_approx = np.dot(A_pinv, A)
print("\nA_pinv와 A의 내적 (근사적인 단위행렬):\n", np.round(identity_approx, 2))

원본 행렬 A (3x2):
 [[1 2]
 [3 4]
 [5 6]]

유사 역행렬 A_pinv (2x3):
 [[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]

A_pinv와 A의 내적 (근사적인 단위행렬):
 [[ 1.  0.]
 [-0.  1.]]


---
### 7. [실무 응용] SVD와 Pseudo Inverse를 활용한 GPS 위치 계산

우리가 매일 사용하는 스마트폰의 GPS는 위성(Satellite)으로부터 **위성의 현재 3차원 위치**와 **신호 송신 시간($t_i$)** 데이터를 받습니다.\n
수신기는 자신의 시계로 **수신 시간($t_{rec}$)**을 측정하여 위성과의 거리(Pseudo-range)를 계산하지만, 스마트폰의 시계는 부정확하기 때문에 **수신기 시계 오차(b)**가 미지수로 추가됩니다.\n

우리가 구해야 할 미지수는 4개($x, y, z, b$)인데, 상용 GPS는 6개 이상의 위성 신호를 잡습니다. 즉, 방정식이 미지수보다 많은 **초과 결정 시스템(Overdetermined System)**이 되므로 역행렬을 직접 구할 수 없습니다.\n
이 때 SVD를 이용한 **유사 역행렬(Pseudo Inverse)**로 가장 오차가 적은 최적의 위치(x, y, z)를 한 번에 계산해냅니다!

In [7]:
import numpy as np

# 빛의 속도 (km/s)
C = 299792.458 

# [1. 시뮬레이션 환경 구성]
# 6개 위성의 임의 3차원 좌표 (고도 약 20,000km 수준)
satellites = np.array([
    [15000, 12000, 20000],
    [-10000, 18000, 22000],
    [1000, -15000, 21000],
    [14000, -10000, 23000],
    [-12000, -8000, 24000],
    [-5000, 16000, 25000]
])

# 사용자의 실제 3차원 위치 (우리가 SVD 역산으로 찾아내야 할 정답)
true_pos = np.array([300, 400, 50])
true_clock_bias = 0.00001 # 수신기의 실제 시간 오차 (초 단위)

# (가상 생성) 위성이 신호를 보낸 시간 t_i 배열 생성
# 실제 거리 / 빛의 속도 = 도달에 걸린 순수 시간
transmit_times = []
receiver_time = 100.0 # 수신기가 신호를 받은 수신기 기준 시간(불안정함)

# 각 위성이 신호를 송신한 시간(t_i)을 역으로 시뮬레이션하여 쏜다고 가정
for sat in satellites:
    real_dist = np.linalg.norm(sat - true_pos)
    pure_travel_time = real_dist / C
    
    # 수신기가 100.0초에 받았다고 할때, 실제 세상 시간은 100.0 - 오차
    true_receiver_time = receiver_time - true_clock_bias
    t_i = true_receiver_time - pure_travel_time
    transmit_times.append(t_i)
transmit_times = np.array(transmit_times)

# --- 여기까지가 GPS 위성 시스템이 허공에 쏜 "숨겨진 정답" 입니다 ---

In [8]:
# [2. 수신기가 데이터를 받아서 Pseudo-range (의사 거리) 측정]
# 수신기는 위성 위치(satellites)와 송신 시간(transmit_times)을 전달받고, 자신의 수신 시간(receiver_time)을 뺍니다.

pseudo_ranges = []
for t_i in transmit_times:
    # P = c * (수신기 시계 시간 - 위성 송신 시간)
    # 이 거리 안에는 (실제 거리 + c*수신기 시간오차) 가 섞여 있습니다.
    noise = np.random.normal(0, 0.001) # 대기권 통과 전파 지연 등 약간의 노이즈
    P_i = C * (receiver_time - t_i) + noise 
    pseudo_ranges.append(P_i)
pseudo_ranges = np.array(pseudo_ranges)


In [9]:
# [3. 선형 방정식 A * x = b 세우기]
# 비선형 모델(구의 방정식)을 위성 1번 식을 뺌으로써 연립 일차 방정식(선형 모델)으로 변환
# 우리가 구할 미지수 배열 x_vec = [x, y, z, C*시계오차]
A = []
b = []

x1, y1, z1 = satellites[0]
P1 = pseudo_ranges[0]

for i in range(1, 6):
    xi, yi, zi = satellites[i]
    Pi = pseudo_ranges[i]
    
    # A 행렬: [ 2(Xi - X1), 2(Yi - Y1), 2(Zi - Z1), -2(Pi - P1) ]
    A_row = [
        2 * (xi - x1),
        2 * (yi - y1),
        2 * (zi - z1),
        -2 * (Pi - P1) # c*d 의 계수
    ]
    A.append(A_row)
    
    # b 벡터: Xi^2 - X1^2 + Yi^2 - Y1^2 + Zi^2 - Z1^2 - Pi^2 + P1^2
    b_val = (xi**2 - x1**2) + (yi**2 - y1**2) + (zi**2 - z1**2) - (Pi**2 - P1**2)
    b.append(b_val)

A = np.array(A) # 크기: 5 x 4
b = np.array(b) # 크기: 5


In [10]:
# [4. 유사 역행렬(Pseudo Inverse)로 해 구하기]
# A는 5x4의 직사각형 행렬이므로 역행렬(A^-1)이 없습니다.
# np.linalg.pinv(A) 를 통해 SVD 기반의 최적해를 도출합니다!
A_pinv = np.linalg.pinv(A)

# 행렬의 내적 연산 (A_pinv * b) 로 x_vec (x, y, z, c*d) 도출
calculated_vec = np.dot(A_pinv, b)

calculated_pos = calculated_vec[:3]
calculated_clock_bias = calculated_vec[3] / C # 오차 거리를 다시 시간(초)으로 복원

print("=== 실제 정답 위치 및 오차 ===")
print(f"X: {true_pos[0]:.2f}, Y: {true_pos[1]:.2f}, Z: {true_pos[2]:.2f}")
print(f"Clock Bias: {true_clock_bias:.6f} 초")

print("\n=== SVD 유사 역행렬로 역산출 한 결과 ===")
print(f"X: {calculated_pos[0]:.2f}, Y: {calculated_pos[1]:.2f}, Z: {calculated_pos[2]:.2f}")
print(f"Clock Bias: {calculated_clock_bias:.6f} 초")

print("\n[결론] 직사각형 행렬 시스템임에도 SVD 덕분에 오차를 최소화한 수신기의 정확한 좌표와 시간까지 알아냈습니다!")

=== 실제 정답 위치 및 오차 ===
X: 300.00, Y: 400.00, Z: 50.00
Clock Bias: 0.000010 초

=== SVD 유사 역행렬로 역산출 한 결과 ===
X: 300.00, Y: 400.00, Z: 50.00
Clock Bias: 0.000010 초

[결론] 직사각형 행렬 시스템임에도 SVD 덕분에 오차를 최소화한 수신기의 정확한 좌표와 시간까지 알아냈습니다!


### 8. 실습 과제 (Mission)

배운 개념을 활용하여 다음 과제를 수행하세요.

1. **Pandas 실습**: `Score`가 90점 이상인 사람들의 데이터만 추출하여 새로운 데이터프레임으로 저장하고 출력하세요. (R의 `subset`을 연상하며 해결)
2. **NumPy 실습**: 1부터 10까지의 숫자가 들어있는 NumPy 배열을 만들고, 모든 요소에 3을 곱한 결과를 브로드캐스팅을 활용해 출력하세요.
3. **JAX 실습 (선택)**: $g(x) = 3x^2 + 2x$ 함수를 정의하고 `jax.grad`를 사용하여 $x=2.0$일 때의 기울기를 구해보세요.

In [3]:
%pip install pandas


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# 1. Pandas 실습 (위의 df 객체 활용) 
# 여기에 코드를 작성하세요
import pandas as pd

# 1. 데이터프레임(df) 생성하기
data = {
    'Name': ['Stella', 'Yara', 'Frank', 'David', 'Yoon'],
    'Score': [85, 92, 78, 100, 95]
}
df = pd.DataFrame(data)

print("--- 원본 데이터프레임 (df) ---")
print(df)
print("\n" + "="*30 + "\n")

# 2. 'Score' 열이 90 이상인 행만 필터링해서 새로운 데이터프레임에 저장
high_score_df = df[df['Score'] >= 90]

print("--- 90점 이상인 사람들의 데이터 (high_score_df) ---")
# 3. 결과 출력
high_score_df


--- 원본 데이터프레임 (df) ---
     Name  Score
0  Stella     85
1    Yara     92
2   Frank     78
3   David    100
4    Yoon     95


--- 90점 이상인 사람들의 데이터 (high_score_df) ---


,Name,Score
1,Yara,92
3,David,100
4,Yoon,95


In [5]:
# 2. NumPy 실습
# 여기에 코드를 작성하세요
import numpy as np
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("A * 3 =", A*3)


A * 3 = [ 3  6  9 12 15 18 21 24 27 30]


In [19]:
# 3. JAX 실습 (선택, jax가 설치되어 있는 경우만)
# 여기에 코드를 작성하세요
import jax

def f(x):
    return 3*x**2 + 2*x

df_dx = jax.grad(f)

x_val = 2.0
print("df_dx =", df_dx(x_val))


df_dx = 14.0


In [28]:
# 4. Pseudo Inverse 실습
# 임의의 4x3 행렬을 만들고 유사 역행렬을 계산해보세요.
# 여기에 코드를 작성하세요
import numpy as np

A = np.array([
    [3,7,0.1,7],
    [0,4,0,-1],
    [1,2,7,1]])

A_Pinv = np.linalg.pinv(A)

print("Pseudo Inverse of A:\n", A_Pinv)

Pseudo Inverse of A:
 [[ 0.03536304 -0.04709937  0.00829506]
 [ 0.02561748  0.20410956 -0.00111852]
 [-0.0270097  -0.02536543  0.14263087]
 [ 0.10246993 -0.18356176 -0.00447409]]


In [45]:
# 5. SVD 실습
# NumPy의 np.random.rand()를 이용해 임의의 5x3 행렬 B를 만들고,
# np.linalg.svd(B)를 적용한 뒤 가장 큰 특이값(Singular Value)을 출력해보세요.
# 여기에 코드를 작성하세요
import numpy as np

# 1. np.random.rand()를 이용해 임의의 5x3 행렬 B 생성
B = np.random.rand(5, 3)
print("행렬 B:\n", B)
print("-" * 30)

# 2. np.linalg.svd(B) 적용
# SVD 함수는 차례로 U(직교행렬), S(특이값 배열), Vh(전치 직교행렬)를 반환합니다.
U, S, Vh = np.linalg.svd(B)

# 3. 가장 큰 특이값 출력
# np.linalg.svd가 반환하는 S는 이미 특이값들이 "내림차순"으로 정렬된 1차원 배열(Vector)입니다.
# 따라서 S 배열의 첫 번째 원소인 S[0]이 가장 큰 특이값이 됩니다.
max_singular_value = S[0]
print("모든 특이값(S):", S)
print("가장 큰 특이값:", max_singular_value)
print("\nLeft singular vectors(U):\n", U)
print("Right singular vectors(Vh):\n", Vh)

행렬 B:
 [[0.30837508 0.84741708 0.44188045]
 [0.59779751 0.29780933 0.88360817]
 [0.16006927 0.21811966 0.98389131]
 [0.41971795 0.79599144 0.88877126]
 [0.28959437 0.99496302 0.31274783]]
------------------------------
모든 특이값(S): [2.27523742 0.88280416 0.30295918]
가장 큰 특이값: 2.2752374233951995

Left singular vectors(U):
 [[ 0.41609284 -0.3793823   0.02030108 -0.47917058 -0.67299275]
 [ 0.44495831  0.43926161 -0.74917983 -0.17574676  0.13001537]
 [ 0.3852164   0.54793059  0.6525181  -0.31081787  0.1702726 ]
 [ 0.55571012  0.00167226  0.10644717  0.79465493 -0.21994547]
 [ 0.41433494 -0.60240151  0.03473569 -0.10688505  0.6729101 ]]
Right singular vectors(Vh):
 [[ 0.35565498  0.62574948  0.69422412]
 [ 0.06746014 -0.75803961  0.64871032]
 [-0.93217952  0.1838846   0.31181371]]
